/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './../routes/__root';
import { Route as LayoutImport } from './../routes/_layout';
import { Route as LayoutIndexImport } from './../routes/_layout/index';
import { Route as LayoutIntermediateImport } from './../routes/_layout/intermediate';
import { Route as LayoutBeginnerImport } from './../routes/_layout/beginner';

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any);

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any);

const LayoutIntermediateRoute = LayoutIntermediateImport.update({
  path: '/intermediate',
  getParentRoute: () => LayoutRoute,
} as any);

const LayoutBeginnerRoute = LayoutBeginnerImport.update({
  path: '/beginner',
  getParentRoute: () => LayoutRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof LayoutImport;
      parentRoute: typeof rootRoute;
    };
    '/_layout/beginner': {
      id: '/_layout/beginner';
      path: '/beginner';
      fullPath: '/beginner';
      preLoaderRoute: typeof LayoutBeginnerImport;
      parentRoute: typeof LayoutImport;
    };
    '/_layout/intermediate': {
      id: '/_layout/intermediate';
      path: '/intermediate';
      fullPath: '/intermediate';
      preLoaderRoute: typeof LayoutIntermediateImport;
      parentRoute: typeof LayoutImport;
    };
    '/_layout/': {
      id: '/_layout/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof LayoutIndexImport;
      parentRoute: typeof LayoutImport;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutBeginnerRoute,
    LayoutIntermediateRoute,
    LayoutIndexRoute,
  }),
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/beginner",
        "/_layout/intermediate",
        "/_layout/"
      ]
    },
    "/_layout/beginner": {
      "filePath": "_layout/beginner.tsx",
      "parent": "/_layout"
    },
    "/_layout/intermediate": {
      "filePath": "_layout/intermediate.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
